# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: off

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install --without release

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

# notifications:
#   - provider: Slack
#     incoming_webhook:
#       secure: zUujuzaZFqpFndOFkoIMkXMFTniWWi0ZtR58PN63c796EcWHJEyOf+XBi81LPrBBKzQYiY1auI1gkNt+ESnJXLxSzY+Q1bbncwN35hc2J84=
